"""AI generation API routes."""

from typing import Annotated, Optional

from fastapi import APIRouter, HTTPException, status
from posthog import capture
from pydantic import BaseModel, Field

from app.dependencies import DbSession, RequiredUser
from app.models import Generation

router = APIRouter(prefix="/api")


# Credit costs per generation type
CREDIT_COSTS = {
    "blog": 10,
    "email": 5,
    "social": 2,
}


class GenerateRequest(BaseModel):
    """Request body for content generation."""
    prompt: str = Field(..., min_length=1, max_length=1000)
    generation_type: str = Field(..., pattern="^(blog|email|social)$")


class GenerateResponse(BaseModel):
    """Response from content generation."""
    id: int
    content: str
    generation_type: str
    credits_used: int
    credits_remaining: int


class CreditsResponse(BaseModel):
    """User credits balance."""
    credits: int


@router.post("/generate", response_model=GenerateResponse)
async def generate_content(
    request: GenerateRequest,
    current_user: RequiredUser,
    db: DbSession,
):
    """Generate AI content (mock implementation).

    This endpoint would integrate with an LLM API in production.
    For testing, it returns a mock response.
    """
    credits_needed = CREDIT_COSTS.get(request.generation_type, 5)

    # Check credits
    if current_user.credits < credits_needed:
        capture("generation_failed_insufficient_credits", properties={
            "generation_type": request.generation_type,
            "credits_needed": credits_needed,
            "credits_available": current_user.credits,
        })
        raise HTTPException(
            status_code=status.HTTP_402_PAYMENT_REQUIRED,
            detail=f"Insufficient credits. Need {credits_needed}, have {current_user.credits}",
        )

    # Deduct credits
    current_user.use_credits(credits_needed)
    db.commit()

    # Mock AI generation (would call OpenAI/Anthropic in production)
    mock_content = _generate_mock_content(request.generation_type, request.prompt)

    # Record generation
    generation = Generation.create(
        db,
        user_id=current_user.id,
        generation_type=request.generation_type,
        prompt=request.prompt,
        result=mock_content,
        credits_used=credits_needed,
    )

    capture("content_generated", properties={
        "generation_type": request.generation_type,
        "credits_used": credits_needed,
        "credits_remaining": current_user.credits,
        "prompt_length": len(request.prompt),
    })

    return GenerateResponse(
        id=generation.id,
        content=mock_content,
        generation_type=request.generation_type,
        credits_used=credits_needed,
        credits_remaining=current_user.credits,
    )


@router.get("/credits", response_model=CreditsResponse)
async def get_credits(current_user: RequiredUser):
    """Get current user's credit balance."""
    return CreditsResponse(credits=current_user.credits)


def _generate_mock_content(generation_type: str, prompt: str) -> str:
    """Generate mock content based on type."""
    templates = {
        "blog": f"# Blog Post\n\nBased on your prompt: {prompt[:50]}...\n\nThis is a mock blog post that would be generated by an AI model. It would contain multiple paragraphs of relevant content.",
        "email": f"Subject: Re: {prompt[:30]}\n\nHi,\n\nThank you for your message. This is a mock email response generated based on your prompt.\n\nBest regards,\nAcme AI",
        "social": f"🚀 {prompt[:100]}... #AI #Generated #AcmeAI",
    }
    return templates.get(generation_type, f"Generated content for: {prompt}")
