source "https://rubygems.org"

ruby "~> 3.3"

gem "sinatra", "~> 4.1"
gem "puma", "~> 6.6"
gem "rackup", "~> 2.2"
gem "posthog-ruby", "~> 3.20"

group :test do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.2"
  gem "rake", "~> 13.3"
end
